apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: express-app-hpa-hackathon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-app-deployment-hackathon
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 80