apiVersion: v1
kind: Service
metadata:
  name: express-app-loadbalancer-service-hackathon
spec:
  selector:
    app: express-app-hackathon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer